//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payement
    {
        public string Payaement_id { get; set; }
        public int An { get; set; }
        public string PayementType { get; set; }
        public Nullable<int> CardNum { get; set; }
    }
}
