//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string Reservation_id { get; set; }
        public string Guest_id { get; set; }
        public string Emplyee_id { get; set; }
        public int RoomNum { get; set; }
        public int An { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Checkout { get; set; }
        public Nullable<int> Totaldays { get; set; }
        public decimal Reservationcost { get; set; }
    }
}
