//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomNum { get; set; }
        public string Description { get; set; }
        public int QteBeds { get; set; }
        public int MaxOccupancy { get; set; }
        public string Availability { get; set; }
        public Nullable<decimal> RoomCost { get; set; }
    }
}
