//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public string Service_id { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceCost { get; set; }
    }
}
